site_name: JujubaSVG
theme:
  name: material
  logo: assets/img/logo.svg
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.footer
    - navigation.instant
    - content.code.annotations # (1)!
    - content.code.copy
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep purple
      accent: light blue

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: deep purple
      accent: blue

nav:
  - Setup ✨:
    - Android: setup/android.md
    - Flutter: setup/flutter.md
  - Available Commands 📐: available-commands.md
  - Contributions 🤝: contributions.md

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.emoji
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
