[versions]
firebase-crashlytics-gradle = "2.9.9"
google-services = "4.4.0"
kotlin = "1.9.20"
compose_bom = "2023.10.01"
compose_ui_version = "1.5.4"
compose_compiler = "1.5.4"
compose_material_3 = "1.1.2"
multidex = "2.0.1"
nav_compose_integration = "2.7.6"
coil = "2.3.0"
appcompat = "1.6.1"
swipe_refresh = "1.2.0-alpha01"
card_view = "1.0.0"
lifecycle = "2.7.0"
preference = "1.2.1"
timber = "5.0.1"
gson = "2.10"
junit = "4.13.2"
android_test = "1.1.3"
truth = "1.1.3"
test_core = "1.5.0"
arch_core = "2.2.0"
mockk = "1.13.8"
coroutines = "1.6.4"
espresso = "3.3.0"
test_rules_version = "1.3.0"
gradle = "8.2.2"
paging_compose = "3.2.1"
firebase-crashlytics-ktx = "18.6.0"
firebase-analytics-ktx = "21.5.0"
android_youtube_player_version = "12.0.0"
agp = "8.0.2"
kotlin1810 = "1.8.10"
core-ktx = "1.12.0"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
material = "1.11.0"
ktlint_plugin = "11.5.1"
ksp = "1.9.20-1.0.13"
kover = "0.7.5"
vanniktech = "0.28.0"

[libraries]
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
swipe_refresh_layout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipe_refresh" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "card_view" }
lifecycle_viewmodel_ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle_compose_runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
preferences_ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preference" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
arc_core_common = { group = "androidx.arch.core", name = "core-common", version.ref = "arch_core" }
arc_core_runtime = { group = "androidx.arch.core", name = "core-runtime", version.ref = "arch_core" }
arc_core_testing = { group = "androidx.arch.core", name = "core-testing", version.ref = "arch_core" }
truth = { group = "com.google.truth", name = "truth", version.ref = "truth" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlinx_coroutines_test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutines" }

compose_ui = { group = "androidx.compose.ui", name = "ui", version.ref = "compose_ui_version" }
compose_preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "compose_ui_version" }
compose_activity = { group = "androidx.activity", name ="activity-compose", version.ref = "compose_ui_version" }
compose_ui_tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "compose_ui_version" }

ui_compose_test = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "compose_compiler" }
compose_material_3 = { group = "androidx.compose.material3", name = "material3", version.ref = "compose_material_3" }
paging_compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging_compose" }
coil = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
navigation_compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "nav_compose_integration" }
test_core = { group = "androidx.test", name = "core", version.ref = "test_core" }
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle" }
kotlin_gradle_plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version.ref = "firebase-crashlytics-ktx" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx", version.ref = "firebase-analytics-ktx" }
android_youtube_player = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "android_youtube_player_version" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
vanniktech_publish = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "vanniktech" }

[bundles]
lifecycle = ["lifecycle_viewmodel_ktx", "lifecycle_compose_runtime"]
test = ["junit", "arc_core_common", "arc_core_runtime", "arc_core_testing", "truth", "mockk", "kotlinx_coroutines_test"]
compose_extras = ["compose_material_3", "navigation_compose", "paging_compose"]
compose_impl = ["compose_ui", "compose_preview", "compose_activity"]
compose_debug_impl = ["compose_ui_tooling"]

[plugins]