lane :update_tag do
  prefix = ENV['PREFIX']
  version_properties_file = "../jujubasvg/version.properties"

  last_tag = sh("git tag --list '#{prefix}*' --sort=-v:refname | head -n 1").strip

  if last_tag.empty?
    UI.message("No tag found with prefix #{prefix}. Creating the first tag 1.0.0.")
    new_tag = "#{prefix}1.0.0"
    sh("git tag #{new_tag}")
    sh("git push origin #{new_tag}")
    UI.success("First tag created: #{new_tag}")
  else
      stripped_tag = last_tag.gsub(prefix, '')
      version_match = stripped_tag.match(/(\d+)\.(\d+)\.(\d+)/)

      minor = stripped_tag[1].to_i + 1
      new_version = "\"#{stripped_tag[0]}.#{minor}.0\""

      if (Gem::Version.new("#{stripped_tag}") <= Gem::Version.new("#{version_static}"))
          new_version = version_static
      end

      new_tag = "#{prefix}#{new_version}"

      File.write(version_properties_file, "VERSION=#{new_version}\n".delete('"'))

      sh("git config user.name 'Rods'")
      sh("git config user.email 'rodrigo.vianna.oliveira@gmail.com'")
      sh("git add #{version_properties_file}")
      sh("git commit -m 'Update version to #{new_version}'")
      sh("git tag #{new_tag}")
      sh("git push origin #{new_tag}")

      UI.success("New tag created: #{new_tag}")
  end
end
