name: 'Setup Flutter'
description: 'Reusable action to setup Flutter environment'

runs:
  using: "composite"
  steps:
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.6' # Set the desired Flutter version