name: Publish flutter to pub.dev

on:
  workflow_dispatch:
  push:
    tags:
      - 'jujubasvg-flutter-[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: ./flutter/jujuba_svg
    permissions:
      id-token: write
